### ISSUE TITLE
Issues while running bash sh

### ISSUE THREAD

**Issue by poorva9** [msainsburydale/NeuralBayesEstimators#1]
Hello, 

I am runnng into the following issue while trying to run the code. I am unable to determine what is causing the issue and how to navigate this. Was hoping I could get some guidance. I have attached a screenshot
Thank you
Regards,
Poorva
![Screenshot (36)](https://github.com/msainsburydale/NeuralBayesEstimators/assets/98067101/43eada7d-8139-43ea-9f66-21c697732b2e)

**Comment by msainsburydale** [comment]
Hi, 

Thanks for opening this issue. The problem was due to an earlier version of our package, [NeuralEstimators](https://github.com/msainsburydale/NeuralEstimators.jl), containing a line of code that was not compatible with Windows (the folder “dev/null” is not present on Windows). This bug has since been fixed, and the package now works on Linux, Mac, and Windows systems. 

I’ve updated the software dependencies for this repo with the new version of NeuralEstimators. Please let me know if any issues persist. 

Best, 
Matt

**Comment by poorva9** [comment]
Hi! Thank you for your help, that seemed to resolve the issue. 
However, after running for a few hours, I seemed to have encountered another issue as such:

```
LoadError: ArgumentError: No file exists at given path: 
C:\Users\poorv\Downloads\Y4S1\FYP\NeuralBayesEstimators\intermediates/GaussianProcess/nuFixed/parameter_configurations/test_xi.rda
Stacktrace:
 [1] checkpath_load
   @ C:\Users\poorv\.julia\packages\FileIO\BE7iZ\src\loadsave.jl:167 [inlined]
 [2] load(::String; options::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:convert,), Tuple{Bool}}})
   @ FileIO C:\Users\poorv\.julia\packages\FileIO\BE7iZ\src\loadsave.jl:110
 [3] loadwithoutdict(path::String, object_name::String)
   @ SpatialDeepSets C:\Users\poorv\Downloads\Y4S1\FYP\NeuralBayesEstimators\src\SpatialDeepSets.jl:154
 [4] Parameters(path::String)
   @ Main C:\Users\poorv\Downloads\Y4S1\FYP\NeuralBayesEstimators\src\GaussianProcess\nuFixed\Parameters.jl:29
 [5] top-level scope
   @ C:\Users\poorv\Downloads\Y4S1\FYP\NeuralBayesEstimators\src\VisualiseRealisations.jl:25
in expression starting at C:\Users\poorv\Downloads\Y4S1\FYP\NeuralBayesEstimators\src\Vis
```

I tried to reinstall the R dependencies as well to navigate the issue, but I could not run it successfully either, encountering this error:

```
Do you want to automatically install package dependencies? (y/n)y
Do you want to ensure that all package versions are as given in Dependencies.txt (this option is only recommended for use if there is a problem with the latest version of the packages)? (y/n)y
When changing the packages to the versions specified in Dependencies.txt, please use your discretion when answering the question “Which would you like to update?”.  Updating all packages (i.e., option 3) may cause errors.Package dependencies are being installed automatically using scripts/Dependencies_install.R
Downloading package from url: https://cran.csiro.au/src/contrib/Archive/evd/evd_2.3-3.tar.gz
Error: Failed to install 'unknown package' from URL:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
Execution halted
```

The nuFixed directory is not being created in the 'intermediates" folder, but nuVaried seems to be created
I was hoping to receive guidance again. My apologies for the inconvenience caused.

Best, 
Poorva

**Comment by msainsburydale** [comment]
Hi Poorva, 

In the first error message, you can see that there are both forward and backward slashes in the filepath:

```
C:\Users\poorv\Downloads\Y4S1\FYP\NeuralBayesEstimators\intermediates/GaussianProcess/nuFixed/parameter_configurations/test_xi.rda
```

This is the source of the error, I believe. I had constructed the file path with forward slashes `/` hard-coded: however, in some cases on Windows, folders should be separated by backward slashes `\`. 

I don't have a Windows computer for testing, but I think I have updated the code to now be Windows compatible. Please let me know if issues persist. 

You mention that the code took several hours to run before breaking: it might be worthwhile to check that the code works with your set-up by first using the "quick" option , as detailed in the readme. 

Best, 
Matt

**Comment by poorva9** [comment]
Hi, 
Unfortunately, Im still running into the same issue with the directory. Im not sure if the issue is just with the backslash, as other directories are being created, but it only runs into error for this particular one. 
```

######## Starting simulation study for GaussianProcess/nuFixed model ############


Visualising realisations from the GaussianProcess/nuFixed model...ERROR:
LoadError: ArgumentError: No file exists at given path: C:\Users\poorv\Downloads\Y4S1\FYP\NeuralBayesEstimators\intermediates\GaussianProcess/nuFixed\parameter_configurations\test_xi.rda
Stacktrace:
 [1] checkpath_load
   @ C:\Users\poorv\.julia\packages\FileIO\BE7iZ\src\loadsave.jl:167 [inlined]
 [2] load(::String; options::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:convert,), Tuple{Bool}}})
   @ FileIO C:\Users\poorv\.julia\packages\FileIO\BE7iZ\src\loadsave.jl:110
 [3] loadwithoutdict(path::String, object_name::String)
   @ SpatialDeepSets C:\Users\poorv\Downloads\Y4S1\FYP\NeuralBayesEstimators\src\SpatialDeepSets.jl:154
 [4] Parameters(path::String)
   @ Main C:\Users\poorv\Downloads\Y4S1\FYP\NeuralBayesEstimators\src\GaussianProcess\nuFixed\Parameters.jl:29
 [5] top-level scope
   @ C:\Users\poorv\Downloads\Y4S1\FYP\NeuralBayesEstimators\src\VisualiseRealisations.jl:25
in expression starting at C:\Users\poorv\Downloads\Y4S1\FYP\NeuralBayesEstimators\src\VisualiseRealisations.jl:23

```
Also, with regards to the quick option, it only prompts me when the code first starts to run. Eventually, the prompt is printed but it just jumps to executing the code without taking in any input from me. Perhaps this is why I am unable to run the code quickly
```
######## Setting up ############

Do you wish to use a very low number of parameter configurations and epochs to quickly establish that the code is working? (y/n)
y

######## Starting the experiments... ############

Do you wish to use a very low number of parameter configurations and epochs to quickly establish that the code is working? (y/n)

######## Starting experiment on approximating the Bayes estimator: Uniform distribution ############

```
Thanks for your help!
Poorva

**Comment by msainsburydale** [comment]
The code was not originally designed to be compatible with Windows. With a colleague, we are working to make it compatible on Windows systems, but it might not be ready until next week. Thanks for your patience. In the meantime, if you're looking to implement neural Bayes estimators, may I suggest you check out our package: [NeuralEstimators](https://github.com/msainsburydale/NeuralEstimators.jl). 

The "quick" prompt is printed every time a new section begins, but your original answer to the prompt is used each time.

**Comment by poorva9** [comment]
> The code was not originally designed to be compatible with Windows. With a colleague, we are working to make it compatible on Windows systems, but it might not be ready until next week. Thanks for your patience. In the meantime, if you're looking to implement neural Bayes estimators, may I suggest you check out our package: [NeuralEstimators](https://github.com/msainsburydale/NeuralEstimators.jl). 
> 
> 
> 
> The "quick" prompt is printed every time a new section begins, but your original answer to the prompt is used each time. 

Hi, 
sure, will do.
Is there any update on this?
Best regards,
Poorva

**Comment by msainsburydale** [comment]
Hi, 

Apologies for the delay. With the help of my colleague the repo now has `bat` scripts that can be executed on Windows (please see the updated README). I also changed the code so that the "quick" prompt is only received once.

You should now be able to run the code on your Windows machine. Please let me know if any problems persist. Also happy to help with implementing the package if needed. 

Best, 
Matt

**Comment by poorva9** [comment]
Hi, I am still running into the error, even after fixing the Windows error. Could it be that there is an error with accessing the folder before it has even been accessed?
Thanks for your help

```
Visualising realisations from the GaussianProcess/nuFixed model...
ERROR: LoadError: ArgumentError: No file exists at given path: C:\Users\poorv\Downloads\Y4S1\FYP\NeuralBayesEstimators\intermediates\GaussianProcess\nuFixed\parameter_configurations\test_xi.rda
Stacktrace:
 [1] checkpath_load
   @ C:\Users\poorv\.julia\packages\FileIO\BE7iZ\src\loadsave.jl:167 [inlined]
 [2] load(::String; options::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:convert,), Tuple{Bool}}})
   @ FileIO C:\Users\poorv\.julia\packages\FileIO\BE7iZ\src\loadsave.jl:110
 [3] loadwithoutdict(path::String, object_name::String)
   @ SpatialDeepSets C:\Users\poorv\Downloads\Y4S1\FYP\NeuralBayesEstimators\src\SpatialDeepSets.jl:157
 [4] Parameters(path::String)
   @ Main C:\Users\poorv\Downloads\Y4S1\FYP\NeuralBayesEstimators\src\GaussianProcess\nuFixed\Parameters.jl:29
 [5] top-level scope
   @ C:\Users\poorv\Downloads\Y4S1\FYP\NeuralBayesEstimators\src\VisualiseRealisations.jl:26
```
